### ISSUE TITLE
ValueError when loading potentials from different iterations. 

### ISSUE THREAD

**Issue by clpetix** [mphowardlab/relentless#249]
Looping through iterations and trying to load a potential raises: `ValueError: Potential name already used`. 

The minimum reproducer for this is having two directories `0` & `1` each with `pair_potential.json` in them. Then running: 

```
import relentless

for i in range(0, 2):
       spline = relentless.model.potential.PairSpline.from_file("{}/pair_potential.json".format(i))
```    
 The traceback is: 
 
```
> Traceback (most recent call last):
  File "load-potential.py", line 4, in <module>
    spline = relentless.model.potential.PairSpline.from_file("{}/pair_potential.0.json".format(i))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "relentless/model/potential/potential.py", line 220, in from_file
    return cls.from_json(data)
           ^^^^^^^^^^^^^^^^^^^
  File "relentless/model/potential/pair.py", line 876, in from_json
    u = super().from_json(data)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "relentless/model/potential/potential.py", line 194, in from_json
    u = cls(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^
  File "relentless/model/potential/pair.py", line 872, in __init__
    super().__init__(types=types, params=params, name=name)
  File "relentless/model/potential/pair.py", line 187, in __init__
    super().__init__(types, params, PairParameters, name)
  File "relentless/model/potential/potential.py", line 145, in __init__
    raise ValueError("Potential name already used")
ValueError: Potential name already used
```

**Comment by mphoward** [comment]
This behavior should not happen because a new potential name is supposed to be automatically selected.

Can you attach the JSON files needed to run this? Also, does this happen only for `PairSpline`, or does it occur for other potentials?

**Comment by clpetix** [comment]
This directory is the reproducer: [error-potential-name.zip](https://github.com/user-attachments/files/15793761/error-potential-name.zip)

I have only had this issue with spline potentials,  but I will test other potentials and let you know!

**Comment by mphoward** [comment]
I think you will see the same issue with other potentials. This line is supposed to handle this issue by defaulting the name if it's already taken:

https://github.com/mphowardlab/relentless/blob/dacdb02c34fc84a2aba7c9b9efc7f576b4d6bfc6/src/relentless/model/potential/potential.py#L178-L179

However, this line:

https://github.com/mphowardlab/relentless/blob/dacdb02c34fc84a2aba7c9b9efc7f576b4d6bfc6/src/relentless/model/potential/potential.py#L142-L143

will then make a default that has the same name as the one that's already taken `__u[1]`. The fix, I think, is that in lines 178-179, the check should be changed to default the name if it matches the pattern `__u[*]`, rather than if it's already taken.
